apiVersion: 1

datasources:
  - name: MySQL-Logs
    type: mysql
    uid: mysql-logs
    url: mysql:3306
    user: cepem_user
    database: cepem_healthcare
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      maxConnLifetime: 14400
    secureJsonData:
      password: "cepem_password"
