// <auto-generated />
using System;
using DatabaseAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260302095635_AddTranslationTable")]
    partial class AddTranslationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("PersonId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ContactEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactEmails");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ContactPhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactPhoneNumbers");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ContactToObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<int>("ObjectType")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ObjectId", "ObjectType", "ContactId")
                        .IsUnique();

                    b.ToTable("ContactToObjects");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.DoctorExaminationRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ExaminationRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ExaminationRoomId");

                    b.ToTable("DoctorExaminationRooms");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NameTranslationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameTranslationId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.DrugCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NameTranslationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameTranslationId");

                    b.ToTable("DrugCategories");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.DrugToDrugCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DrugId");

                    b.ToTable("DrugToDrugCategories");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.DrugUse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("EventId");

                    b.ToTable("DrugUses");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.EmailHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UsedTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("EmailHistories");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PasswordExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<Guid?>("EventGroupId")
                        .HasColumnType("char(36)");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HappenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HappenedTo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NameTranslationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameTranslationId");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Examination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("ExaminationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ExaminationTypeId");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ExaminationRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("ExaminationRooms");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ExaminationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NameTranslationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameTranslationId");

                    b.ToTable("ExaminationTypes");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.FirstNameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UsedTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("FirstNameHistories");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyIco")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentHospitalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("ParentHospitalId");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.HospitalEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HospitalId");

                    b.ToTable("HospitalEmployees");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.HospitalEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("HospitalId");

                    b.ToTable("HospitalEquipment");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Injury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("InjuryTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("InjuryTypeId");

                    b.ToTable("Injuries");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.InjuryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NameTranslationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameTranslationId");

                    b.ToTable("InjuryTypes");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.LastNameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UsedTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("LastNameHistories");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Alive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceNumber")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.PatientDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EncryptedPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientDocuments");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.PatientSymptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("SymptomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SymptomId");

                    b.ToTable("PatientSymptoms");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleAfter")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleBefore")
                        .HasColumnType("longtext");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("CommentId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.PhoneNumberHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UsedFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UsedTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PhoneNumberHistories");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Pregnancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("Result")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Pregnancies");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExaminationRoomId")
                        .HasColumnType("int");

                    b.Property<int>("ExaminationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ExaminationRoomId");

                    b.HasIndex("ExaminationTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NameTranslationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameTranslationId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NameTranslationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameTranslationId");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CS")
                        .HasColumnType("longtext");

                    b.Property<string>("EN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NL")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("VaccineTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("VaccineTypeId");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.VaccineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NameTranslationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameTranslationId");

                    b.ToTable("VaccineTypes");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Appointment", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.HospitalEmployee", "HospitalEmployee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Equipment", "Equipment")
                        .WithMany("Appointments")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("DatabaseAPI.DatabaseModels.Hospital", "Hospital")
                        .WithMany("Appointments")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Person", "Person")
                        .WithMany("Appointments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Hospital");

                    b.Navigation("HospitalEmployee");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ContactEmail", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Contact", "Contact")
                        .WithMany("Emails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ContactPhoneNumber", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Contact", "Contact")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ContactToObject", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Contact", "Contact")
                        .WithMany("ContactToObjects")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Hospital", null)
                        .WithMany("ContactToObjects")
                        .HasForeignKey("HospitalId");

                    b.HasOne("DatabaseAPI.DatabaseModels.Person", null)
                        .WithMany("ContactToObjects")
                        .HasForeignKey("PersonId");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.DoctorExaminationRoom", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Employee", "Doctor")
                        .WithMany("ExaminationRooms")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.ExaminationRoom", "ExaminationRoom")
                        .WithMany("DoctorExaminationRooms")
                        .HasForeignKey("ExaminationRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("ExaminationRoom");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Drug", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Translation", "NameTranslation")
                        .WithMany()
                        .HasForeignKey("NameTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NameTranslation");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.DrugCategory", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Translation", "NameTranslation")
                        .WithMany()
                        .HasForeignKey("NameTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NameTranslation");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.DrugToDrugCategory", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.DrugCategory", "Category")
                        .WithMany("DrugToDrugCategories")
                        .HasForeignKey("CategoryId");

                    b.HasOne("DatabaseAPI.DatabaseModels.Drug", "Drug")
                        .WithMany("DrugToDrugCategories")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.DrugUse", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Drug", "Drug")
                        .WithMany("DrugUses")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Event", "Event")
                        .WithMany("DrugUses")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.EmailHistory", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Person", "Person")
                        .WithMany("EmailHistories")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Employee", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Person", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("DatabaseAPI.DatabaseModels.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Event", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Comment", "Comment")
                        .WithMany("Events")
                        .HasForeignKey("CommentId");

                    b.HasOne("DatabaseAPI.DatabaseModels.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Patient", "Patient")
                        .WithMany("Events")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("EventType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.EventType", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Translation", "NameTranslation")
                        .WithMany()
                        .HasForeignKey("NameTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NameTranslation");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Examination", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Event", "Event")
                        .WithMany("Examinations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.ExaminationType", "ExaminationType")
                        .WithMany("Examinations")
                        .HasForeignKey("ExaminationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("ExaminationType");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ExaminationRoom", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ExaminationType", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Translation", "NameTranslation")
                        .WithMany()
                        .HasForeignKey("NameTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NameTranslation");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.FirstNameHistory", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Person", "Person")
                        .WithMany("FirstNameHistories")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Hospital", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Address", "Address")
                        .WithOne("Hospital")
                        .HasForeignKey("DatabaseAPI.DatabaseModels.Hospital", "AddressId");

                    b.HasOne("DatabaseAPI.DatabaseModels.Hospital", "ParentHospital")
                        .WithMany("ChildHospitals")
                        .HasForeignKey("ParentHospitalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("ParentHospital");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.HospitalEmployee", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Employee", "Employee")
                        .WithMany("HospitalEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Hospital", "Hospital")
                        .WithMany("HospitalEmployees")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.HospitalEquipment", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Equipment", "Equipment")
                        .WithMany("HospitalEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Hospital", "Hospital")
                        .WithMany("HospitalEquipments")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Injury", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Event", "Event")
                        .WithMany("Injuries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.InjuryType", "InjuryType")
                        .WithMany("Injuries")
                        .HasForeignKey("InjuryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("InjuryType");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.InjuryType", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Translation", "NameTranslation")
                        .WithMany()
                        .HasForeignKey("NameTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NameTranslation");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.LastNameHistory", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Person", "Person")
                        .WithMany("LastNameHistories")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Patient", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Comment", "Comment")
                        .WithMany("Patients")
                        .HasForeignKey("CommentId");

                    b.HasOne("DatabaseAPI.DatabaseModels.Person", "Person")
                        .WithOne("Patient")
                        .HasForeignKey("DatabaseAPI.DatabaseModels.Patient", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.PatientDocument", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Patient", "Patient")
                        .WithMany("Documents")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.PatientSymptom", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Event", "Event")
                        .WithMany("PatientSymptoms")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Symptom", "Symptom")
                        .WithMany("PatientSymptoms")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Person", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Address", "Address")
                        .WithOne("Person")
                        .HasForeignKey("DatabaseAPI.DatabaseModels.Person", "AddressId");

                    b.HasOne("DatabaseAPI.DatabaseModels.Comment", "Comment")
                        .WithMany("Persons")
                        .HasForeignKey("CommentId");

                    b.Navigation("Address");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.PhoneNumberHistory", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Person", "Person")
                        .WithMany("PhoneNumberHistories")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Pregnancy", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Event", "Event")
                        .WithMany("Pregnancies")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Reservation", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Employee", "Doctor")
                        .WithMany("Reservations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.ExaminationRoom", "ExaminationRoom")
                        .WithMany("Reservations")
                        .HasForeignKey("ExaminationRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.ExaminationType", "ExaminationType")
                        .WithMany("Reservations")
                        .HasForeignKey("ExaminationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Patient", "Patient")
                        .WithMany("Reservations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("ExaminationRoom");

                    b.Navigation("ExaminationType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Role", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Translation", "NameTranslation")
                        .WithMany()
                        .HasForeignKey("NameTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NameTranslation");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Symptom", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Translation", "NameTranslation")
                        .WithMany()
                        .HasForeignKey("NameTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NameTranslation");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.UserRole", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.Person", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Vaccine", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Event", "Event")
                        .WithMany("Vaccines")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseAPI.DatabaseModels.VaccineType", "VaccineType")
                        .WithMany("Vaccines")
                        .HasForeignKey("VaccineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("VaccineType");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.VaccineType", b =>
                {
                    b.HasOne("DatabaseAPI.DatabaseModels.Translation", "NameTranslation")
                        .WithMany()
                        .HasForeignKey("NameTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NameTranslation");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Address", b =>
                {
                    b.Navigation("Hospital");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Comment", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Patients");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Contact", b =>
                {
                    b.Navigation("ContactToObjects");

                    b.Navigation("Emails");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Drug", b =>
                {
                    b.Navigation("DrugToDrugCategories");

                    b.Navigation("DrugUses");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.DrugCategory", b =>
                {
                    b.Navigation("DrugToDrugCategories");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Employee", b =>
                {
                    b.Navigation("ExaminationRooms");

                    b.Navigation("HospitalEmployees");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Equipment", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HospitalEquipments");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Event", b =>
                {
                    b.Navigation("DrugUses");

                    b.Navigation("Examinations");

                    b.Navigation("Injuries");

                    b.Navigation("PatientSymptoms");

                    b.Navigation("Pregnancies");

                    b.Navigation("Vaccines");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ExaminationRoom", b =>
                {
                    b.Navigation("DoctorExaminationRooms");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.ExaminationType", b =>
                {
                    b.Navigation("Examinations");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Hospital", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ChildHospitals");

                    b.Navigation("ContactToObjects");

                    b.Navigation("HospitalEmployees");

                    b.Navigation("HospitalEquipments");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.HospitalEmployee", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.InjuryType", b =>
                {
                    b.Navigation("Injuries");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Patient", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Events");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Person", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ContactToObjects");

                    b.Navigation("EmailHistories");

                    b.Navigation("Employee");

                    b.Navigation("FirstNameHistories");

                    b.Navigation("LastNameHistories");

                    b.Navigation("Patient");

                    b.Navigation("PhoneNumberHistories");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.Symptom", b =>
                {
                    b.Navigation("PatientSymptoms");
                });

            modelBuilder.Entity("DatabaseAPI.DatabaseModels.VaccineType", b =>
                {
                    b.Navigation("Vaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
